language: ruby

services:
  - docker

before_install:
- pip install --user codecov > /dev/null
- docker-compose up -d > /dev/null
- echo Sleeping for 300 seconds for the containers source code to properly build
- sleep 300
- echo Done sleeping

after_success:
  - codecov --file coverage/lcov.info --disable search

script:
- docker exec copytube_phpfpm vendor/bin/phpunit
- docker exec copytube_phpfpm php artisan dusk
- docker exec copytube_socket npm run testTS
- docker exec copytube_realtime deno test --allow-net
