language: ruby

services:
  - docker

before_install:
- pip install --user codecov
- docker-compose up -d
- sleep 300

after_success:
  - codecov --file coverage/lcov.info --disable search

script:
- docker exec copytube_phpfpm vendor/bin/phpunit
- docker exec copytube_socket node_modules/.bin/mocha -r ts-node/register test/**/*.ts
- docker exec copytube_realtime deno test
