version: '3'

services:

  nginx:
    container_name: copytube_nginx
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    volumes:
      - ./src/copytube:/var/www/copytube
    working_dir: /var/www/copytube
    depends_on:
      - phpfpm
      - socket
    ports:
      - "9002:9002"
    networks:
      - copytube-network

  phpfpm:
    container_name: copytube_phpfpm
    build:
      context: .
      dockerfile: .docker/phpfpm.dockerfile
    depends_on:
      - sql
    env_file:
      - ./.docker/env/phpfpm.env
    ports:
      - "9000:9000"
    volumes:
      - ./src/copytube:/var/www/copytube
    # Run commands after volumes are mounted. The php-fpm cmd is here so the container doesnt exit after running the composer command
    command: bash -c "composer install && npm i && npm run dev && php-fpm -F"
    working_dir: /var/www/copytube
    networks:
      - copytube-network

  sql:
    container_name: copytube_sql
    build:
      context: .
      dockerfile: .docker/sql.dockerfile
    ports:
      - "3007:3006"
    env_file:
      - ./.docker/env/sql.env
    networks:
      - copytube-network

  socket:
    container_name: copytube_socket
    build:
      context: .
      dockerfile: .docker/node.dockerfile
    volumes:
      - ./src/socket:/var/www/socket
    ports:
      - "9009:9009"
    working_dir: /var/www/socket
    command: bash -c "npm i --verbose && node_modules/.bin/tsc && pm2-runtime ecosystem.config.js"
    networks:
      - copytube-network

  redis:
    container_name: copytube_redis
    build:
      context: .
      dockerfile: .docker/redis.dockerfile
    ports:
      - "6379:6379"
    networks:
      - copytube-network

  realtime:
    container_name: copytube_realtime
    build:
      context: .
      dockerfile: .docker/drash.dockerfile
    volumes:
      - ./src/realtime:/var/www/realtime
    ports:
      - "9008:9008"
    working_dir: /var/www/realtime
    command: bash -c "deno --allow-net --allow-read --allow-run --allow-env --allow-write app.ts"
    networks:
      - copytube-network

#  asterisk:
#    container_name: copytube_asterisk
#    image: hibou/asterisk:14
#    ports:
#      - "5060:5060/udp"
#      - "5060:5060/tcp"
#      - "10000-10099:10000-10099/udp"
#      - "8088:8088"
#      - "8089:8089"
#    volumes:
#      - "./.docker/config/asterisk/conf:/etc/asterisk"
#    labels:
#      - "traefik.enable=false"

networks:
  copytube-network:
    driver: bridge
