version: '3'

services:

  nginx:
    container_name: copytube_nginx
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    volumes:
      - ./src/copytube:/var/www/copytube
    working_dir: /var/www/copytube
    depends_on:
      - phpfpm
    ports:
      - "9002:9002"
    networks:
      - copytube-network

  phpfpm:
    container_name: copytube_phpfpm
    build:
      context: .
      dockerfile: .docker/phpfpm.dockerfile
    depends_on:
      - sql
    env_file:
      - ./.docker/env/phpfpm.env
    ports:
      - "9000:9000"
    volumes:
      - ./src/copytube:/var/www/copytube
    # Run commands after volumes are mounted. The php-fpm cmd is here so the container doesnt exit after running the composer command
    command: bash -c "composer install && php-fpm -F"
    working_dir: /var/www/copytube
    networks:
      - copytube-network

  sql:
    container_name: copytube_sql
    build:
      context: .
      dockerfile: .docker/sql.dockerfile
    ports:
      - "3007:3006"
    env_file:
      - ./.docker/env/sql.env
    networks:
      - copytube-network

  node:
    container_name: api_node
    build:
      context: .
      dockerfile: .docker/node.dockerfile
    volumes:
      - ./src/api:/var/www/api
    working_dir: /var/www/api
    command: bash -c "npm i --verbose && pm2-runtime ecosystem.config.js"
    networks:
      - copytube-network

  mongodb:
    container_name: api_mongo
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - ./.docker/env/mongodb.env
    networks:
      - copytube-network

networks:
  copytube-network:
    driver: bridge
