version: '3'

services:

  nginx:
    container_name: copytube_nginx
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    volumes:
      - ./src/copytube:/var/www/copytube
    working_dir: /var/www/copytube
    depends_on:
      - phpfpm
      - realtime
    ports:
      - "9002:9002"
    networks:
      - copytube-network

# Something we can use in place of execing into the phpfpm container, eg `docker-compose up --config docker-compose.yml -d && docker-compose up --config docker-compose.dusk.yml
#  dusk:
#    container_name: copytube_dusk
#    image: chilio/laravel-dusk-ci:php-8.0
#    volumes:
#    - ./src/copytube:/var/www/copytube
#    working_dir: /var/www/copytube
#    command: bash -c "php artisan dusk"
#    networks:
#      - copytube-network

  phpfpm:
    container_name: copytube_phpfpm
    build:
      context: .
      dockerfile: .docker/phpfpm.dockerfile
    depends_on:
      - sql
    env_file:
      - ./.docker/env/phpfpm.env
    ports:
      - "9000:9000"
    command: bash -c "php-fpm -F"
    volumes:
      - ./src/copytube/app:/var/www/copytube/app
      - ./src/copytube/config:/var/www/copytube/config
      - ./src/copytube/routes:/var/www/copytube/routes
      - ./src/copytube/database:/var/www/copytube/database
      - ./src/copytube/resources:/var/www/copytube/resources
      - ./src/copytube/composer.json:/var/www/copytube/composer.json
      - ./src/copytube/webpack.mix.js:/var/www/copytube/webpack.mix.js
      - ./src/copytube/.env:/var/www/copytube/.env
      - ./src/copytube/tests:/var/www/copytube/tests
    # Run commands after volumes are mounted. The php-fpm cmd is here so the container doesnt exit after running the composer command
    networks:
      - copytube-network

  sql:
    container_name: copytube_sql
    image: mysql:8
    ports:
      - "3007:3006"
    env_file:
      - ./.docker/env/sql.env
    networks:
      - copytube-network

  redis:
    container_name: copytube_redis
#build:
    ##      context: .
    ##      dockerfile: .docker/redis.dockerfile
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - copytube-network

  selenium:
    image: selenium/standalone-chrome
    networks:
      - copytube-network

  realtime:
    container_name: copytube_realtime
    build:
      context: .
      dockerfile: .docker/drash.dockerfile
    volumes:
      - ./src/realtime:/var/www/realtime
    ports:
      - "9008:9008"
    working_dir: /var/www/realtime
    command: bash -c "deno run --allow-net --allow-read --allow-run --allow-env --allow-write app.ts"
    networks:
      - copytube-network

networks:
  copytube-network:
    driver: bridge
