version: '3'

services:

  nginx:
    container_name: copytube_nginx
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    volumes:
      - ./src/copytube/public:/var/www/copytube/public
    working_dir: /var/www/copytube
    depends_on:
      - phpfpm
      - realtime
    ports:
      - "9002:9002"
    networks:
      - copytube-network

  phpfpm:
    container_name: copytube_phpfpm
    build:
      context: .
      dockerfile: .docker/phpfpm.dockerfile
    environment:
      - XDEBUG=true
    depends_on:
      - sql
    shm_size: '2gb'
    ports:
      - "9000:9000"
    command: bash -c "php-fpm -F"
    volumes:
      - ./src/copytube/app:/var/www/copytube/app
      - ./src/copytube/config:/var/www/copytube/config
      - ./src/copytube/routes:/var/www/copytube/routes
      - ./src/copytube/database:/var/www/copytube/database
      - ./src/copytube/resources:/var/www/copytube/resources
      - ./src/copytube/composer.json:/var/www/copytube/composer.json
      - ./src/copytube/webpack.mix.js:/var/www/copytube/webpack.mix.js
      - ./src/copytube/.env:/var/www/copytube/.env
      - ./src/copytube/tests:/var/www/copytube/tests
      - ./src/copytube/storage:/var/www/copytube/storage
    # Run commands after volumes are mounted. The php-fpm cmd is here so the container doesnt exit after running the composer command
    networks:
      - copytube-network

  sql:
    container_name: copytube_sql
    image: mysql:8
    ports:
      - "3007:3006"
    env_file:
      - ./.docker/env/sql.env
    networks:
      - copytube-network

  redis:
    container_name: copytube_redis
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - copytube-network

  # selenium:
  #   image: selenium/standalone-chrome
  #   networks:
  #     - copytube-network
  #   shm_size: '2gb'
    # ports:
    #   - "4444:4444"

  realtime:
    container_name: copytube_realtime
    build:
      context: .
      dockerfile: .docker/drash.dockerfile
    volumes:
      - ./src/realtime:/var/www/realtime
    ports:
      - "9008:9008"
    working_dir: /var/www/realtime
    command: bash -c "deno run --allow-net --allow-read --allow-run --allow-env --allow-write app.ts"
    networks:
      - copytube-network

networks:
  copytube-network:
    driver: bridge
