version: '3'

services:

  nginx:
    container_name: copytube_nginx
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    volumes:
      - ./src/copytube:/var/www/copytube
    working_dir: /var/www/copytube
    depends_on:
      - phpfpm
    ports:
      - "9002:9002"
    networks:
      - copytube-network

  phpfpm:
    container_name: copytube_phpfpm
    build:
      context: .
      dockerfile: .docker/phpfpm.dockerfile
    depends_on:
      - sql
    ports:
      - "9000:9000"
    volumes:
      - ./src/copytube:/var/www/copytube
    working_dir: /var/www/copytube
    networks:
      - copytube-network

  sql:
    container_name: copytube_sql
    build:
      context: .
      dockerfile: .docker/sql.dockerfile
    ports:
      - "3007:3006"
    env_file:
      - ./.docker/env/sql.env
    networks:
      - copytube-network

networks:
  copytube-network:
    driver: bridge
