name: Docker

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'src/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'src/**'

jobs:

  docker-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start Docker
        run: docker-compose up -d > /dev/null