name: master

#on:
#  push:
#    branches: [ master ]
#    paths:
#      - 'src/realtime/*'
#  pull_request:
#    branches: [ master ]
#    paths:
#      - 'src/realtime/*'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Laravel Tests
        run: |
          cd src/copytube
          php ../../composer.phar install
          npm i
          npm run dev
          docker-compose build > /dev/null
          docker-compose up -f docker-compose-test.yml

  realtime-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Realtime Tests
        run: |
          docker-compose up -d > /dev/null
          docker exec copytube_realtime deno test -A tests/integration/tests.ts
          docker exec copytube_realtime deno test -A  tests/unit/tests.ts

  realtime-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Deno
        uses: denolib/setup-deno@v2
      - name: Realtime Linter
        run: |
          cd src/realtime
          deno fmt --check
          deno lint --unstable
