name: master

#on:
#  push:
#    branches: [ master ]
#    paths:
#      - 'src/realtime/*'
#  pull_request:
#    branches: [ master ]
#    paths:
#      - 'src/realtime/*'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  laravel-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/copytube
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer

      - name: Format Checks
        run: |
          npm ci
          npm run fmt:check

      - name: Laravel Tests
        run: |
          npm ci
          composer install
          npm run dev
          docker-compose up -d > /dev/null
          docker exec copytube_phpfpm vendor/bin/phpunit
#          docker exec copytube_phpfpm php artisan dusk

  realtime-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Realtime Linter Check
        run: |
          cd src/realtime
          deno lint --unstable

      - name: Realtime Format Check
        run: |
          cd src/realtime
          deno format --check

      - name: Realtime Tests
        run: |
          docker-compose up -d > /dev/null
          sleep 20
          docker exec copytube_realtime deno test -A tests/integration/tests.ts
          docker exec copytube_realtime deno test -A  tests/unit/tests.ts

  realtime-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Deno
        uses: denolib/setup-deno@v2
      - name: Realtime Linter
        run: |
          cd src/realtime
          deno fmt --check
          deno lint --unstable
