name: master

#on:
#  push:
#    branches: [ master ]
#    paths:
#      - 'src/realtime/*'
#  pull_request:
#    branches: [ master ]
#    paths:
#      - 'src/realtime/*'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  laravel-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/copytube
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Format Checks
        run: |
          npm run fmt:check

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8'
          tools: composer

      - name: Lint Checks
        run: |
          composer install
          composer dump-autoload -o
          composer lint

  laravel-backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Laravel Backend Tests
        env:
          DEBUGBAR_ENABLE: false
        run: |
          docker-compose up -d sql
          docker-compose build --parallel --build-arg XDEBUG_MODE="coverage" redis phpfpm
          docker-compose up -d redis phpfpm > /dev/null
          docker exec copytube_phpfpm php artisan migrate
          docker exec copytube_phpfpm php artisan db:seed
          docker exec copytube_phpfpm vendor/bin/phpunit --coverage-clover=coverage.xml
          docker exec copytube_phpfpm ls
          docker cp copytube_phpfpm:/var/www/copytube/coverage.xml .
      
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          file: coverage.xml
          name: copytube-copytube

#  laravel-frontend-tests:
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: src/copytube
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Setup PHP and Composer
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: '8'
#          tools: composer
#
#
#      - name: Laravel Frontend Tests
#        run: |
#          npm ci > /dev/null
#          composer install > /dev/null
#          npm run dev > /dev/null
#          docker-compose build --parallel
#          docker-compose up -d > /dev/null
#          sleep 12
#          docker exec copytube_phpfpm make test_dusk
##         docker exec copytube_phpfpm php artisan dusk tests/Browser/Components/AddCommentComponentTest.php
##         docker exec copytube_phpfpm php artisan dusk:install

  realtime-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Realtime Linter Check
        run: |
          cd src/realtime
          deno lint --unstable

      - name: Realtime Format Check
        run: |
          cd src/realtime
          deno fmt --check

  realtime-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Realtime Tests
        run: |
          docker-compose build --parallel redis realtime
          docker-compose up -d redis realtime
          sleep 20
          docker exec copytube_realtime deno test --coverage=cov -A tests
          docker exec copytube_realtime deno coverage cov
          docker exec copytube_realtime deno coverage --lcov cov > cov.lcov
      - name: Upload Coverage
        uses: codecov/codecov-action@v2.1.0
        with:
          name: copytube-realtime
          files: cov.lcov
