name: master

#on:
#  push:
#    branches: [ master ]
#    paths:
#      - 'src/realtime/*'
#  pull_request:
#    branches: [ master ]
#    paths:
#      - 'src/realtime/*'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  laravel-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/copytube
    steps:
      - uses: actions/checkout@v2

      - name: Format Checks
        run: |
          npm run fmt:check

  laravel-backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/copytube
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8'
          tools: composer

      - name: Laravel Backend Tests
        run: |
          npm ci
          composer install
          npm run dev
          docker-compose up -d > /dev/null
          sleep 8
          docker exec copytube_phpfpm vendor/bin/phpunit

  laravel-frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/copytube
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8'
          tools: composer

      - name: Laravel Frontend Tests
        run: |
          npm ci > /dev/null
          composer install > /dev/null
          npm run dev > /dev/null
          docker-compose up -d > /dev/null
          sleep 8
          docker exec copytube_phpfpm curl http://copytube_nginx:9002
          docker exec copytube_phpfpm php artisan dusk tests/Browser/Components/AddCommentComponentTest.php

  realtime-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@v2
      - name: Realtime Linter Check
        run: |
          cd src/realtime
          deno lint --unstable

      - name: Realtime Format Check
        run: |
          cd src/realtime
          deno fmt --check

  realtime-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@v2

      - name: Realtime Tests
        run: |
          docker-compose up -d > /dev/null
          sleep 20
          docker exec copytube_realtime deno test -A tests/integration/tests.ts
          docker exec copytube_realtime deno test -A  tests/unit/tests.ts
