name: master

#on:
#  push:
#    branches: [ master ]
#    paths:
#      - 'src/realtime/*'
#  pull_request:
#    branches: [ master ]
#    paths:
#      - 'src/realtime/*'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  laravel-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format Checks
        run: |
          cd src/copytube
          npm ci
          npm run fmt:check

      - name: Laravel Tests
        run: |
          docker-compose up -d > /dev/null
          sleep 400
          docker exec copytube_phpfpm vendor/bin/phpunit
#          docker exec copytube_phpfpm php artisan dusk

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

      - name: Lint Check
        run: |
          cd src/copytube
          composer install
          composer lint

  realtime-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Realtime Tests
        run: |
          docker-compose up -d > /dev/null
          sleep 20
          docker exec copytube_realtime deno test -A tests/integration/tests.ts
          docker exec copytube_realtime deno test -A  tests/unit/tests.ts

  realtime-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Deno
        uses: denolib/setup-deno@v2
      - name: Realtime Linter
        run: |
          cd src/realtime
          deno fmt --check
          deno lint --unstable
