name: Realtime

on:
  push:
    branches: [ master ]
    paths:
      - 'src/realtime/*'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/realtime/*'

jobs:

  realtime-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start Docker
        run: docker-compose up -d
      - name: Run Tests
        run: docker exec copytube_realtime deno test