name: Socket

on:
  push:
    branches: [ master ]
    paths:
      - 'src/socket/*'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/socket/*'

jobs:

  socket-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start Docker and run tests
        run: |
          docker-compose up -d > /dev/null
          sleep 60
          docker exec copytube_socket /var/www/socket/node_modules/.bin/mocha -r ts-node/register test/**/*.ts
#      - name: Run Tests
#        run: docker exec copytube_socket npm run test